package com.nowayhome.housecheck.application

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(DocumentIntakeAiProperties::class)
class DocumentIntakeExtractionConfiguration
